version: '3.1'

services:

  sharly-gui:
    build:
      context: packages/gui
    ports:
      - 8083:80
    environment:
      SHARLY_BACKEND_HOST: sharly-backend
      SHARLY_BACKEND_PORT: 8082
    restart: always
    networks:
      - sharly-net

  mongo:
    image: mongo
    restart: always
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: toor
    networks:
      - sharly-net

  sharly-backend:
    build:
      context: packages/backend
    restart: always
    environment:
      DB_HOST: mongo
      DB_USER: root
      DB_PASSWD: toor
      SHARLY_PASSWD: sharly
    networks:
      - sharly-net

networks:
  sharly-net:
    driver: bridge
