version: '3.1'

services:

  mongo:
    image: mongo
    restart: always
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: toor
    networks:
      - sharly-net

  mongo-express:
    image: mongo-express
    restart: always
    depends_on:
      - mongo
    ports:
      - 8185:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: toor
    networks:
      - sharly-net

  sharly-backend:
    build:
      context: .
    restart: always
    environment:
      DB_HOST: mongo
      DB_USER: root
      DB_PASSWD: toor
      SHARLY_PASSWD: sharly
    networks:
      - sharly-net
    ports:
      - 8082:8082

networks:
  sharly-net:
    driver: bridge
